apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: poc-idp-lab-catalog-repository
  description: Source of truth for the Backstage catalog in the IDP lab (catalog entities and software templates).
  annotations:
    github.com/project-slug: ozeta/poc-idp-lab-catalog-repository
    backstage.io/techdocs-ref: dir:.
  tags:
    - backstage
    - catalog
    - platform
    - idp
  links:
    - url: https://github.com/ozeta/poc-idp-lab-catalog-repository
      title: GitHub Repository
      icon: github
    - url: 'https://teams.microsoft.com/l/channel/19%3AwpFJUbTuaBuIhhecEj5mt5URreZw7EET_BG1Ro6pI181%40thread.tacv2/DevEx?groupId=5944ba60-15cf-4b5c-b359-a7819160e34a&tenantId=8ca5db88-a5ab-48f7-a5e0-4ce50935f807&ngc=true'
      title: Microsoft Teams Channel
spec:
  type: documentation
  lifecycle: experimental
  owner: HylandSandbox
  system: local-dev
